{
 "title": "Token Economics",
 "description": "Token Economics Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "FinOps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "(3 / 3600) / (rate(vllm:generation_tokens_total[1m]) > 0) * 1e6",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prompt vs Generation tokens/sec",
   "type": "timeseries",
   "description": "Prompt vs Generation tokens/sec",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(vllm:prompt_tokens_total[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(vllm:generation_tokens_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU utilization %",
   "type": "timeseries",
   "description": "GPU utilization %",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "DCGM_FI_DEV_GPU_UTIL", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Output tokens/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(vllm:generation_tokens_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}